version: '3'
services:
  controller-service:
    build:
      context: controller
    ports:
        - "8080:8080"
  pdf-compose-service:
    build:
      context: server
    ports:
        - "8090:8090"